### ISSUE TITLE
clarify timing expectations for firehose

### ISSUE THREAD

**Issue by ktdreyer** [librariesio/firehose#280]
Would you please clarify how soon we should see an event here in the firehose compared to publishing it upstream?

For example, if I push a new tag to GitHub, how long would I have to wait until I see it in the libraries.io firehose? Is libraries.io listening an event stream that GitHub publishes somewhere? Or is libraries.io polling GitHub on some interval?

**Comment by ktdreyer** [comment]
I found the `Watcher` class at https://github.com/librariesio/dispatch/blob/master/dispatch.rb . There's `EventMachine.add_periodic_timer(30)`, so I guess this is polling all those upstream feeds every 30 seconds.

**Comment by katzj** [comment]
The upstream feeds get polled with that frequency... github gets instead watched off of the github sse stream

**Comment by ktdreyer** [comment]
Thanks, I've added this to the README here: https://github.com/librariesio/firehose/pull/281
