### ISSUE TITLE
Open source it! 

### ISSUE THREAD

**Issue by andrew** [librariesio/firehose#4]
Related to https://github.com/librariesio/libraries/issues/185

- [x] License
- [x] Contributing.md
- [x] Code_of_conduct.md
- [ ] Setup docs in readme
- [ ] SECURITY.md
- [ ] Write some tests!
- [ ] Setup on travis-ci.org
- [ ] Add favicon

**Comment by nelsonic** [comment]
Add the `favicon` to the static site to avoid `404` error:
![libraries-firehose-stream](https://cloud.githubusercontent.com/assets/194400/11641659/5cdc95e4-9d31-11e5-919f-2397516f8ff9.png)

**Comment by andrew** [comment]
Thanks @nelsonic, have added it to the todo list
