### ISSUE TITLE
nodemon not listed in dependencies but required to npm start

### ISSUE THREAD

**Issue by nelsonic** [librariesio/firehose#6]
Hi guys, the `package.json` is making an *assumption* that *everyone* has `nodemon` installed globally on their machine... https://github.com/librariesio/firehose/blob/16cfc81e0a8025a488d76e0eda5bc5c2d124d126/package.json#L10
![nodemon-not-found](https://cloud.githubusercontent.com/assets/194400/11608351/a66ff338-9b5e-11e5-88b2-7c17fd10021c.png)

Could we make the dependency *explicit*?

**Comment by andrew** [comment]
@nelsonic agreed, we should have that as a proper dependency in package.json

**Comment by nelsonic** [comment]
Am I OK to PR the change?

**Comment by andrew** [comment]
Absolutely!
