### ISSUE TITLE
Error: Cannot find module 'babel/register'

### ISSUE THREAD

**Issue by nelsonic** [librariesio/firehose#7]
Hi, I tried to update the dependencies because a few are out-of-date: [![Dependency Status](https://david-dm.org/librariesio/firehose.svg)](https://david-dm.org/librariesio/firehose)
but then When I attempt to run the app locally, I see the error **Error: Cannot find module 'babel/register'**
![cannot-find-babel-register](https://cloud.githubusercontent.com/assets/194400/11634511/d971caee-9d08-11e5-90a6-cc3b0c9965e1.png)

The makers of `babel` have made `babel/register` its own npm package: https://www.npmjs.com/package/babel-register which I have added to `package.json`
Please let me know if that is OK. 

![firehose-works-after-dependency-update](https://cloud.githubusercontent.com/assets/194400/11638364/8c55e8e2-9d1e-11e5-9052-cadfe44c9935.png)

The app boots and *appears* to be working, however given the absence of tests its not possible to *confirm* without review from a @malditogeek

**Comment by andrew** [comment]
:+1:
